### ISSUE TITLE
Value ProductionAcActivePower missing in list of channels after update to 2.16

### ISSUE THREAD

**Issue by stefan73** [Skeletitor/ha_addon_fenecon2mqtt#19]
Upgraded from 2.14 to 2.16 with deinstall/reinstall. 
After reinstall  sum/ProductionAcActivePower was missing. 
The value though still works when I edit it into the configuration. So I think it has been forgotton in the updated config.yaml

**Comment by Skeletitor** [comment]
Hi Stef. 
Thank you verify much. I was so proud to provide a sorted list that I’ve simply forgotten to add it again. 😉

I’ll add it a release a new version during the next days.

**Comment by benniju** [comment]
What do you need this value for? For me it seems to be unknown anyways. Dou you have other inverters that are included in the FEMS?
I think it should not be included in the default configuration if that is the use-case that you use it for, as you can simply add it yourself in that case.

**Comment by Skeletitor** [comment]
Good point. 
I can’t check right now if this entity has an other value than ‘unknown’. 
@stefan73  what values are shown in your case?

**Comment by stefan73** [comment]
The value shows the production of my 3rd string, which is my northern roof. This string connects to a Kaco inverter. This inverter talks to the fenecon system over Modbus using a Socomec Countis E24. AFAIK this is the standard way that fenecon recommends to add inverters.
Removing it from the default config is ok for me. I though guess that the majority of users will not get such edit steps done.

**Comment by benniju** [comment]
Yep I think that most users only have the one Inverter. Maybe you could add it to the README instead.

**Comment by Skeletitor** [comment]
Okay, I'll close that issue here for now. I'll add a statement about the _sum/ProductionAcActivePower entity in the documentation
