### ISSUE TITLE
[BUG] - Reported battery voltage is factor 10 too high. 

### ISSUE THREAD

**Issue by stefan73** [Skeletitor/ha_addon_fenecon2mqtt#20]
Reported battery voltage is factor 10 too high. 

1. Check value of sensor.battery_inverter_fems_battery0_tower0packvoltage
2. Compare to value in SolarGo App from GoodWe (manufacturer of the Fenecon inverter). OR go to your FEMS webpage and watch the live system log.
3. Values the same if you divide the sensor value by 10.

Not sure why this happens. Probably the websocket interface reports this value too high.

![image](https://github.com/Skeletitor/ha_addon_fenecon2mqtt/assets/11725734/f654301a-a03b-42f3-abcd-3fe01ed873b8)
![image](https://github.com/Skeletitor/ha_addon_fenecon2mqtt/assets/11725734/7e2d1274-3433-42db-a73c-42078e76bed8)

Versions:
all up to now
used here
HA 2024.5.4
Fenecon2Mqtt 0.2.16

**Comment by Skeletitor** [comment]
Hi,

sorry for being late here. Benniju is right.  This addon just transport the values from FEMS.

I'll close this issue.

**Comment by stefan73** [comment]
I think the mistake is that you are just making assumptions about the units of the values that Fenecon exports. Fenecon decided for whatever reason to publish voltages in deciVolts. The script takes the value and publishes this into HA as Volts.
The bug is not on the side of Fenecon unless they would have guaranteed the value to be in Volts. The bug is happening at the point where the data gets published into a format that has a unit. Thus the correction needs to happen at that place.
Factuallly the results of the integration is plain wrong.

**Comment by Skeletitor** [comment]
Sorry. But you’re assuming that Fenecon is using dV as a unit. But in reality FEMS delivers the value as dV and the unit in V. So, no it’s not related to this addon.

**Comment by benniju** [comment]
You can just add this line to sensor_overwrite in the Addon config:
```
- >-
    battery0/Tower0PackVoltage;voltage;measurement;V;{{value | int /
    10}};FEMS: battery0/Tower0PackVoltage
```

This is my full sensor_overwrite:

```
sensor_overwrite:
  - channel;device_class;state_class;device_unit;value_template;name
  - >-
    battery0/Tower0PackVoltage;voltage;measurement;V;{{value | int /
    10}};Live-FEMS: battery0/Tower0PackVoltage
  - >-
    ctrlGridOptimizedCharge0/TargetEpochSeconds;timestamp;measurement;;{{value |
    int(0) | as_datetime()}};Live-FEMS:
    ctrlGridOptimizedCharge0/TargetEpochSeconds
```

**Comment by benniju** [comment]
Many units in the API are just plain wrong, but Fenecon doesn't care about that, which I can understand, because strictly these channels are neither shown on any dashboards nor are the channels expect sum documented in any way. I think we should probably happy that we have such a relatively open API, although not all things are perfect.
