### ISSUE TITLE
[BUG] - Data not showed in Energy Dashboard

### ISSUE THREAD

**Issue by 8ear** [Skeletitor/ha_addon_fenecon2mqtt#22]
**Describe the bug**
I have the add on integrated and the data are integrated into MQTT. HA finds the sensors and shows it correctly in a normal dashboard. But the Energy dashboard is empty.
After some research I think that the statistics are empty.
But another issue is that my disk runs out of space. I have already added 100GB more space, and it looks that the storage runs out of space.

Could you help why no statistics data are stored for this data?

**To Reproduce**
1. install addon and configure addon
2. configure devices for energy dashboard
3. no data will be shown in energy dashboard

**Expected behavior**
I see my data in the energy dashboard

**Screenshots**

**Versions:**
 Core 2024.7.3
Supervisor 2024.06.2
Operating System 12.4 
Fenecon2Mqtt Current version: 0.2.16

**Add-On config**
fems_request_channels:
  - _sum/ConsumptionActiveEnergy
  - _sum/ConsumptionActivePower
  - _sum/ConsumptionActivePowerL1
  - _sum/ConsumptionActivePowerL2
  - _sum/ConsumptionActivePowerL3
  - _sum/ConsumptionMaxActivePower
  - _sum/EssActivePower
  - _sum/EssActivePowerL1
  - _sum/EssActivePowerL2
  - _sum/EssActivePowerL3
  - _sum/EssActiveChargeEnergy
  - _sum/EssActiveDischargeEnergy
  - _sum/EssDcChargeEnergy
  - _sum/EssDcDischargeEnergy
  - _sum/EssDischargeEnergy
  - _sum/EssSoc
  - _sum/GridActivePower
  - _sum/GridActivePowerL1
  - _sum/GridActivePowerL2
  - _sum/GridActivePowerL3
  - _sum/GridBuyActiveEnergy
  - _sum/GridMaxActivePower
  - _sum/GridMinActivePower
  - _sum/GridMode
  - _sum/GridSellActiveEnergy
  - _sum/ProductionActiveEnergy
  - _sum/ProductionActivePower
  - _sum/ProductionDcActualPower
  - _sum/ProductionMaxActivePower
  - _sum/State
  - battery0/Soh
  - battery0/Tower0NoOfCycles
  - battery0/Tower0PackVoltage
  - battery0/Current
  - battery0/Voltage
  - batteryInverter0/AirTemperature
  - batteryInverter0/ArmFmVersion
  - batteryInverter0/BmsPackTemperature
  - batteryInverter0/DspFmVersionMaster
  - batteryInverter0/DspFmVersionSlave
  - batteryInverter0/RadiatorTemperature
  - charger0/ActualPower
  - charger0/ActualEnergy
  - charger0/Current
  - charger0/State
  - charger0/Voltage
  - charger1/ActualPower
  - charger1/ActualEnergy
  - charger1/Current
  - charger1/State
  - charger1/Voltage
  - charger1/Voltage
  - ess0/Capacity
  - ess0/DcDischargePower

**Overview of you local EnergyStorage installation**
What is here required?

**Additional context**
Before I used your addon I used it directly with Modbus, it works but not perfect. I used some stuff directly as rest sensor hich works ok. But I wouldn't create all configurations on my own via rest if there is so a nice Addon.

**Comment by Skeletitor** [comment]
Hi. Did you configure the dashboard to use the correct sensors?
e.g.:
![image](https://github.com/user-attachments/assets/fa531953-bdc9-45d9-b7d3-54840cc252e4)

In my installation the statistics are stored and used in the energy dashboard without issues.  

Regarding your database size. Im not able to reproduce this. 

Please keep in mind. There are some issues with the autodiscovery feature since FEMS version 2024.06.01

**Comment by Skeletitor** [comment]
DB size: 
Maybe you can use https://my.home-assistant.io/redirect/supervisor_addon/?addon=a0d7b954_sqlite-web to investigate the sensors  consuming too much space. 
It’s nicely described here: https://community.home-assistant.io/t/how-to-keep-your-recorder-database-size-under-control/295795

But sometimes it is like it is. Provide disk space or reduce the amount of sensors ;)

**Comment by 8ear** [comment]
Hi,
yes the sensors are correct, because some time it works correctly. So I know that it can work.
the DB size is at 7GB. So I don't think it is so much space.
My problem is more that it does not work. :-)

![grafik](https://github.com/user-attachments/assets/7a0a27df-6cc6-4015-8842-7da41a6bd82c)


Statistic doesn't changed:
![grafik](https://github.com/user-attachments/assets/75a3a08c-2a9c-4d16-b998-5630b9b24e9d)

But I saw that the live values are changed.


For example here:
![grafik](https://github.com/user-attachments/assets/cb38616a-f309-421a-931e-e72901991b18)


My configured energy sensors:
![grafik](https://github.com/user-attachments/assets/ea3e2134-0b2f-4b78-9f4f-96a000f2be6f)



Before I used your addon I used the same stuff via modbus and direct rest api without issues. So it looks like the live view works from MQTT directly. But the energy dashboard data come from statistics which does not work.


Kind regards

**Comment by 8ear** [comment]
I will try it.Von: Skeletitor ***@***.***>Gesendet: Donnerstag, 8. August 2024 14:36An: Skeletitor/ha_addon_fenecon2mqttCc: Max H.; AuthorBetreff: Re: [Skeletitor/ha_addon_fenecon2mqtt] [BUG] - Data not showed in Energy Dashboard (Issue #22) 
Could you please try the new version 0.2.17?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Skeletitor/ha_addon_fenecon2mqtt/issues/22#issuecomment-2275715126",
"url": "https://github.com/Skeletitor/ha_addon_fenecon2mqtt/issues/22#issuecomment-2275715126",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Skeletitor** [comment]
<img width="1424" alt="image" src="https://github.com/user-attachments/assets/88b901f0-7157-4ec8-a167-8d7b5f4c6b79">
This is my configuration. I tested with a fresh HA installation yesterday evening and it worked without any issues. -> IÄ'm pretty sure it's a local issue not causes by this add-on.

My Database size is 3.2GB. But I have no experience if there is any size limit which can cause such issues.
